"""Tests for db2bibtex.compare: matching Zotero library entries against a
database backup export by publication_id (not citation key or tag), which
must work across mixed-vintage library items.

Fixture note/keywords text below is generated by calling the real
exporter.build_bibtex_entry() rather than hand-typed, so it carries the
real escape_bibtex() escaping (e.g. "publication\\_id 100", not
"publication_id 100"). A hand-typed, unescaped fixture previously let
PUB_ID_RE regress silently -- it never matched real exporter output, but
these tests stayed green because the fixtures didn't reflect what
escape_bibtex() actually produces. See compare.py's PUB_ID_RE docstring
for the fix.
"""

from __future__ import annotations

import re

from db2bibtex import exporter
from db2bibtex.compare import find_missing, write_missing


def _row(publication_id, pub_number, title, author, pub_year, catalog_id):
    """Minimal row dict for exporter.build_bibtex_entry (missing fields
    default to None via dict.get, same pattern as test_exporter.py's
    and2135_row fixture)."""
    return {
        "publication_id": publication_id,
        "catalog_id": catalog_id,
        "pub_number": pub_number,
        "author": author,
        "pub_year": pub_year,
        "title": title,
        "reference_type": "Journal Article",
    }


def _swap_cite_key(entry_text, new_key):
    """Replace an entry's citation key text only, simulating a library item
    imported under the older Author+Year+Title heuristic (see exporter.py's
    make_cite_key) instead of the current 'AND<pub_number>' convention. The
    note/keywords text is untouched, real, escaped exporter output."""
    return re.sub(r"^(@\w+\{)[^,]+,", rf"\1{new_key},", entry_text, count=1)


ROW_100 = _row(100, 100, "Modern Forest Study", "Smith, Jane", "1975", 5001)
ROW_200 = _row(200, 200, "Stream Chemistry Trends", "Doe, John", "1990", 5002)
ROW_300 = _row(300, 300, "Snowpack Dynamics", "Lee, Pat", "2005", 5003)

_backup_entry_100 = exporter.build_bibtex_entry(ROW_100, used_keys=set())
_backup_entry_200 = exporter.build_bibtex_entry(ROW_200, used_keys=set())
_backup_entry_300 = exporter.build_bibtex_entry(ROW_300, used_keys=set())

BACKUP_BIB = "\n\n".join([_backup_entry_100, _backup_entry_200, _backup_entry_300])

# Library holds pub 100 under a pre-"AND<pub_number>" heuristic citation key
# (an older import) and pub 200 under the current convention; pub 300 was
# never imported into the library, so it's the one expected to show up as
# missing.
_library_entry_100 = _swap_cite_key(
    exporter.build_bibtex_entry(ROW_100, used_keys=set()), "Smith1975Modern"
)
_library_entry_200 = exporter.build_bibtex_entry(ROW_200, used_keys=set())

LIBRARY_BIB = "\n\n".join([_library_entry_100, _library_entry_200])


def test_find_missing_matches_across_mixed_citation_key_vintages(tmp_path):
    backup_path = tmp_path / "backup.bib"
    library_path = tmp_path / "library.bib"
    backup_path.write_text(BACKUP_BIB, encoding="utf-8")
    library_path.write_text(LIBRARY_BIB, encoding="utf-8")

    missing_ids, backup_ids, library_ids, backup_unparsed = find_missing(
        str(backup_path), str(library_path)
    )

    assert missing_ids == ["300"]
    assert set(backup_ids) == {"100", "200", "300"}
    assert set(library_ids) == {"100", "200"}
    assert backup_unparsed == []


def test_write_missing_writes_only_missing_entries(tmp_path):
    backup_path = tmp_path / "backup.bib"
    library_path = tmp_path / "library.bib"
    output_path = tmp_path / "missing.bib"
    backup_path.write_text(BACKUP_BIB, encoding="utf-8")
    library_path.write_text(LIBRARY_BIB, encoding="utf-8")

    missing_ids, backup_ids, _, _ = find_missing(str(backup_path), str(library_path))
    write_missing(missing_ids, backup_ids, str(output_path), str(backup_path), str(library_path))

    written = output_path.read_text(encoding="utf-8")
    assert "@article{AND300," in written
    assert "AND100" not in written
    assert "AND200" not in written


def test_backup_entry_with_no_parseable_publication_id_is_reported_and_excluded(tmp_path):
    backup_bib = BACKUP_BIB + """
@misc{NoPubID,
  title = {Untracked Note},
  note = {No source database reference here},
}
"""
    backup_path = tmp_path / "backup.bib"
    library_path = tmp_path / "library.bib"
    output_path = tmp_path / "missing.bib"
    backup_path.write_text(backup_bib, encoding="utf-8")
    library_path.write_text(LIBRARY_BIB, encoding="utf-8")

    missing_ids, backup_ids, _, backup_unparsed = find_missing(
        str(backup_path), str(library_path)
    )

    assert len(backup_unparsed) == 1
    assert "NoPubID" in backup_unparsed[0]
    assert missing_ids == ["300"]
    assert set(backup_ids) == {"100", "200", "300"}

    write_missing(missing_ids, backup_ids, str(output_path), str(backup_path), str(library_path))
    written = output_path.read_text(encoding="utf-8")
    assert "NoPubID" not in written
